package com.sanelee.zhiyuan.Model;

import java.util.ArrayList;
import java.util.List;

public class GaoKaoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public GaoKaoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Integer value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Integer value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Integer value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Integer value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Integer value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Integer> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Integer> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Integer value1, Integer value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Integer value1, Integer value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(Integer value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(Integer value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(Integer value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(Integer value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(Integer value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<Integer> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<Integer> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(Integer value1, Integer value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andScidIsNull() {
            addCriterion("scid is null");
            return (Criteria) this;
        }

        public Criteria andScidIsNotNull() {
            addCriterion("scid is not null");
            return (Criteria) this;
        }

        public Criteria andScidEqualTo(Integer value) {
            addCriterion("scid =", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotEqualTo(Integer value) {
            addCriterion("scid <>", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidGreaterThan(Integer value) {
            addCriterion("scid >", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidGreaterThanOrEqualTo(Integer value) {
            addCriterion("scid >=", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidLessThan(Integer value) {
            addCriterion("scid <", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidLessThanOrEqualTo(Integer value) {
            addCriterion("scid <=", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidIn(List<Integer> values) {
            addCriterion("scid in", values, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotIn(List<Integer> values) {
            addCriterion("scid not in", values, "scid");
            return (Criteria) this;
        }

        public Criteria andScidBetween(Integer value1, Integer value2) {
            addCriterion("scid between", value1, value2, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotBetween(Integer value1, Integer value2) {
            addCriterion("scid not between", value1, value2, "scid");
            return (Criteria) this;
        }

        public Criteria andAverageIsNull() {
            addCriterion("average is null");
            return (Criteria) this;
        }

        public Criteria andAverageIsNotNull() {
            addCriterion("average is not null");
            return (Criteria) this;
        }

        public Criteria andAverageEqualTo(Integer value) {
            addCriterion("average =", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageNotEqualTo(Integer value) {
            addCriterion("average <>", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageGreaterThan(Integer value) {
            addCriterion("average >", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageGreaterThanOrEqualTo(Integer value) {
            addCriterion("average >=", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageLessThan(Integer value) {
            addCriterion("average <", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageLessThanOrEqualTo(Integer value) {
            addCriterion("average <=", value, "average");
            return (Criteria) this;
        }

        public Criteria andAverageIn(List<Integer> values) {
            addCriterion("average in", values, "average");
            return (Criteria) this;
        }

        public Criteria andAverageNotIn(List<Integer> values) {
            addCriterion("average not in", values, "average");
            return (Criteria) this;
        }

        public Criteria andAverageBetween(Integer value1, Integer value2) {
            addCriterion("average between", value1, value2, "average");
            return (Criteria) this;
        }

        public Criteria andAverageNotBetween(Integer value1, Integer value2) {
            addCriterion("average not between", value1, value2, "average");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(Integer value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(Integer value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(Integer value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(Integer value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(Integer value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(Integer value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<Integer> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<Integer> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(Integer value1, Integer value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(Integer value1, Integer value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andMinIsNull() {
            addCriterion("min is null");
            return (Criteria) this;
        }

        public Criteria andMinIsNotNull() {
            addCriterion("min is not null");
            return (Criteria) this;
        }

        public Criteria andMinEqualTo(Integer value) {
            addCriterion("min =", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotEqualTo(Integer value) {
            addCriterion("min <>", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinGreaterThan(Integer value) {
            addCriterion("min >", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinGreaterThanOrEqualTo(Integer value) {
            addCriterion("min >=", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinLessThan(Integer value) {
            addCriterion("min <", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinLessThanOrEqualTo(Integer value) {
            addCriterion("min <=", value, "min");
            return (Criteria) this;
        }

        public Criteria andMinIn(List<Integer> values) {
            addCriterion("min in", values, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotIn(List<Integer> values) {
            addCriterion("min not in", values, "min");
            return (Criteria) this;
        }

        public Criteria andMinBetween(Integer value1, Integer value2) {
            addCriterion("min between", value1, value2, "min");
            return (Criteria) this;
        }

        public Criteria andMinNotBetween(Integer value1, Integer value2) {
            addCriterion("min not between", value1, value2, "min");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNull() {
            addCriterion("school_id is null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIsNotNull() {
            addCriterion("school_id is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolIdEqualTo(Integer value) {
            addCriterion("school_id =", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotEqualTo(Integer value) {
            addCriterion("school_id <>", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThan(Integer value) {
            addCriterion("school_id >", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("school_id >=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThan(Integer value) {
            addCriterion("school_id <", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdLessThanOrEqualTo(Integer value) {
            addCriterion("school_id <=", value, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdIn(List<Integer> values) {
            addCriterion("school_id in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotIn(List<Integer> values) {
            addCriterion("school_id not in", values, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdBetween(Integer value1, Integer value2) {
            addCriterion("school_id between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andSchoolIdNotBetween(Integer value1, Integer value2) {
            addCriterion("school_id not between", value1, value2, "schoolId");
            return (Criteria) this;
        }

        public Criteria andMinSectionIsNull() {
            addCriterion("min_section is null");
            return (Criteria) this;
        }

        public Criteria andMinSectionIsNotNull() {
            addCriterion("min_section is not null");
            return (Criteria) this;
        }

        public Criteria andMinSectionEqualTo(Integer value) {
            addCriterion("min_section =", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionNotEqualTo(Integer value) {
            addCriterion("min_section <>", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionGreaterThan(Integer value) {
            addCriterion("min_section >", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_section >=", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionLessThan(Integer value) {
            addCriterion("min_section <", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionLessThanOrEqualTo(Integer value) {
            addCriterion("min_section <=", value, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionIn(List<Integer> values) {
            addCriterion("min_section in", values, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionNotIn(List<Integer> values) {
            addCriterion("min_section not in", values, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionBetween(Integer value1, Integer value2) {
            addCriterion("min_section between", value1, value2, "minSection");
            return (Criteria) this;
        }

        public Criteria andMinSectionNotBetween(Integer value1, Integer value2) {
            addCriterion("min_section not between", value1, value2, "minSection");
            return (Criteria) this;
        }

        public Criteria andMaxIsNull() {
            addCriterion("max is null");
            return (Criteria) this;
        }

        public Criteria andMaxIsNotNull() {
            addCriterion("max is not null");
            return (Criteria) this;
        }

        public Criteria andMaxEqualTo(Integer value) {
            addCriterion("max =", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxNotEqualTo(Integer value) {
            addCriterion("max <>", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxGreaterThan(Integer value) {
            addCriterion("max >", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxGreaterThanOrEqualTo(Integer value) {
            addCriterion("max >=", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxLessThan(Integer value) {
            addCriterion("max <", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxLessThanOrEqualTo(Integer value) {
            addCriterion("max <=", value, "max");
            return (Criteria) this;
        }

        public Criteria andMaxIn(List<Integer> values) {
            addCriterion("max in", values, "max");
            return (Criteria) this;
        }

        public Criteria andMaxNotIn(List<Integer> values) {
            addCriterion("max not in", values, "max");
            return (Criteria) this;
        }

        public Criteria andMaxBetween(Integer value1, Integer value2) {
            addCriterion("max between", value1, value2, "max");
            return (Criteria) this;
        }

        public Criteria andMaxNotBetween(Integer value1, Integer value2) {
            addCriterion("max not between", value1, value2, "max");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameIsNull() {
            addCriterion("local_province_name is null");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameIsNotNull() {
            addCriterion("local_province_name is not null");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameEqualTo(String value) {
            addCriterion("local_province_name =", value, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameNotEqualTo(String value) {
            addCriterion("local_province_name <>", value, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameGreaterThan(String value) {
            addCriterion("local_province_name >", value, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameGreaterThanOrEqualTo(String value) {
            addCriterion("local_province_name >=", value, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameLessThan(String value) {
            addCriterion("local_province_name <", value, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameLessThanOrEqualTo(String value) {
            addCriterion("local_province_name <=", value, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameLike(String value) {
            addCriterion("local_province_name like", value, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameNotLike(String value) {
            addCriterion("local_province_name not like", value, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameIn(List<String> values) {
            addCriterion("local_province_name in", values, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameNotIn(List<String> values) {
            addCriterion("local_province_name not in", values, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameBetween(String value1, String value2) {
            addCriterion("local_province_name between", value1, value2, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalProvinceNameNotBetween(String value1, String value2) {
            addCriterion("local_province_name not between", value1, value2, "localProvinceName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameIsNull() {
            addCriterion("local_batch_name is null");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameIsNotNull() {
            addCriterion("local_batch_name is not null");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameEqualTo(String value) {
            addCriterion("local_batch_name =", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotEqualTo(String value) {
            addCriterion("local_batch_name <>", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameGreaterThan(String value) {
            addCriterion("local_batch_name >", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameGreaterThanOrEqualTo(String value) {
            addCriterion("local_batch_name >=", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameLessThan(String value) {
            addCriterion("local_batch_name <", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameLessThanOrEqualTo(String value) {
            addCriterion("local_batch_name <=", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameLike(String value) {
            addCriterion("local_batch_name like", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotLike(String value) {
            addCriterion("local_batch_name not like", value, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameIn(List<String> values) {
            addCriterion("local_batch_name in", values, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotIn(List<String> values) {
            addCriterion("local_batch_name not in", values, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameBetween(String value1, String value2) {
            addCriterion("local_batch_name between", value1, value2, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andLocalBatchNameNotBetween(String value1, String value2) {
            addCriterion("local_batch_name not between", value1, value2, "localBatchName");
            return (Criteria) this;
        }

        public Criteria andSpnameIsNull() {
            addCriterion("spname is null");
            return (Criteria) this;
        }

        public Criteria andSpnameIsNotNull() {
            addCriterion("spname is not null");
            return (Criteria) this;
        }

        public Criteria andSpnameEqualTo(String value) {
            addCriterion("spname =", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameNotEqualTo(String value) {
            addCriterion("spname <>", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameGreaterThan(String value) {
            addCriterion("spname >", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameGreaterThanOrEqualTo(String value) {
            addCriterion("spname >=", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameLessThan(String value) {
            addCriterion("spname <", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameLessThanOrEqualTo(String value) {
            addCriterion("spname <=", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameLike(String value) {
            addCriterion("spname like", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameNotLike(String value) {
            addCriterion("spname not like", value, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameIn(List<String> values) {
            addCriterion("spname in", values, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameNotIn(List<String> values) {
            addCriterion("spname not in", values, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameBetween(String value1, String value2) {
            addCriterion("spname between", value1, value2, "spname");
            return (Criteria) this;
        }

        public Criteria andSpnameNotBetween(String value1, String value2) {
            addCriterion("spname not between", value1, value2, "spname");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameIsNull() {
            addCriterion("local_type_name is null");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameIsNotNull() {
            addCriterion("local_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameEqualTo(Integer value) {
            addCriterion("local_type_name =", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameNotEqualTo(Integer value) {
            addCriterion("local_type_name <>", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameGreaterThan(Integer value) {
            addCriterion("local_type_name >", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameGreaterThanOrEqualTo(Integer value) {
            addCriterion("local_type_name >=", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameLessThan(Integer value) {
            addCriterion("local_type_name <", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameLessThanOrEqualTo(Integer value) {
            addCriterion("local_type_name <=", value, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameIn(List<Integer> values) {
            addCriterion("local_type_name in", values, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameNotIn(List<Integer> values) {
            addCriterion("local_type_name not in", values, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameBetween(Integer value1, Integer value2) {
            addCriterion("local_type_name between", value1, value2, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andLocalTypeNameNotBetween(Integer value1, Integer value2) {
            addCriterion("local_type_name not between", value1, value2, "localTypeName");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(Integer value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(Integer value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(Integer value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(Integer value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(Integer value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<Integer> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<Integer> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(Integer value1, Integer value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(Integer value1, Integer value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andProscoreIsNull() {
            addCriterion("proscore is null");
            return (Criteria) this;
        }

        public Criteria andProscoreIsNotNull() {
            addCriterion("proscore is not null");
            return (Criteria) this;
        }

        public Criteria andProscoreEqualTo(String value) {
            addCriterion("proscore =", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreNotEqualTo(String value) {
            addCriterion("proscore <>", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreGreaterThan(String value) {
            addCriterion("proscore >", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreGreaterThanOrEqualTo(String value) {
            addCriterion("proscore >=", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreLessThan(String value) {
            addCriterion("proscore <", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreLessThanOrEqualTo(String value) {
            addCriterion("proscore <=", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreLike(String value) {
            addCriterion("proscore like", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreNotLike(String value) {
            addCriterion("proscore not like", value, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreIn(List<String> values) {
            addCriterion("proscore in", values, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreNotIn(List<String> values) {
            addCriterion("proscore not in", values, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreBetween(String value1, String value2) {
            addCriterion("proscore between", value1, value2, "proscore");
            return (Criteria) this;
        }

        public Criteria andProscoreNotBetween(String value1, String value2) {
            addCriterion("proscore not between", value1, value2, "proscore");
            return (Criteria) this;
        }

        public Criteria andAreanameIsNull() {
            addCriterion("areaname is null");
            return (Criteria) this;
        }

        public Criteria andAreanameIsNotNull() {
            addCriterion("areaname is not null");
            return (Criteria) this;
        }

        public Criteria andAreanameEqualTo(String value) {
            addCriterion("areaname =", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameNotEqualTo(String value) {
            addCriterion("areaname <>", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameGreaterThan(String value) {
            addCriterion("areaname >", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameGreaterThanOrEqualTo(String value) {
            addCriterion("areaname >=", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameLessThan(String value) {
            addCriterion("areaname <", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameLessThanOrEqualTo(String value) {
            addCriterion("areaname <=", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameLike(String value) {
            addCriterion("areaname like", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameNotLike(String value) {
            addCriterion("areaname not like", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameIn(List<String> values) {
            addCriterion("areaname in", values, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameNotIn(List<String> values) {
            addCriterion("areaname not in", values, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameBetween(String value1, String value2) {
            addCriterion("areaname between", value1, value2, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameNotBetween(String value1, String value2) {
            addCriterion("areaname not between", value1, value2, "areaname");
            return (Criteria) this;
        }

        public Criteria andIs985IsNull() {
            addCriterion("is985 is null");
            return (Criteria) this;
        }

        public Criteria andIs985IsNotNull() {
            addCriterion("is985 is not null");
            return (Criteria) this;
        }

        public Criteria andIs985EqualTo(Integer value) {
            addCriterion("is985 =", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985NotEqualTo(Integer value) {
            addCriterion("is985 <>", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985GreaterThan(Integer value) {
            addCriterion("is985 >", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985GreaterThanOrEqualTo(Integer value) {
            addCriterion("is985 >=", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985LessThan(Integer value) {
            addCriterion("is985 <", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985LessThanOrEqualTo(Integer value) {
            addCriterion("is985 <=", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985In(List<Integer> values) {
            addCriterion("is985 in", values, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985NotIn(List<Integer> values) {
            addCriterion("is985 not in", values, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985Between(Integer value1, Integer value2) {
            addCriterion("is985 between", value1, value2, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985NotBetween(Integer value1, Integer value2) {
            addCriterion("is985 not between", value1, value2, "is985");
            return (Criteria) this;
        }

        public Criteria andIs211IsNull() {
            addCriterion("is211 is null");
            return (Criteria) this;
        }

        public Criteria andIs211IsNotNull() {
            addCriterion("is211 is not null");
            return (Criteria) this;
        }

        public Criteria andIs211EqualTo(Integer value) {
            addCriterion("is211 =", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211NotEqualTo(Integer value) {
            addCriterion("is211 <>", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211GreaterThan(Integer value) {
            addCriterion("is211 >", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211GreaterThanOrEqualTo(Integer value) {
            addCriterion("is211 >=", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211LessThan(Integer value) {
            addCriterion("is211 <", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211LessThanOrEqualTo(Integer value) {
            addCriterion("is211 <=", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211In(List<Integer> values) {
            addCriterion("is211 in", values, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211NotIn(List<Integer> values) {
            addCriterion("is211 not in", values, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211Between(Integer value1, Integer value2) {
            addCriterion("is211 between", value1, value2, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211NotBetween(Integer value1, Integer value2) {
            addCriterion("is211 not between", value1, value2, "is211");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassIsNull() {
            addCriterion("isDoubleFirstClass is null");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassIsNotNull() {
            addCriterion("isDoubleFirstClass is not null");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassEqualTo(Integer value) {
            addCriterion("isDoubleFirstClass =", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassNotEqualTo(Integer value) {
            addCriterion("isDoubleFirstClass <>", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassGreaterThan(Integer value) {
            addCriterion("isDoubleFirstClass >", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDoubleFirstClass >=", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassLessThan(Integer value) {
            addCriterion("isDoubleFirstClass <", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassLessThanOrEqualTo(Integer value) {
            addCriterion("isDoubleFirstClass <=", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassIn(List<Integer> values) {
            addCriterion("isDoubleFirstClass in", values, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassNotIn(List<Integer> values) {
            addCriterion("isDoubleFirstClass not in", values, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassBetween(Integer value1, Integer value2) {
            addCriterion("isDoubleFirstClass between", value1, value2, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassNotBetween(Integer value1, Integer value2) {
            addCriterion("isDoubleFirstClass not between", value1, value2, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gaokao
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 20 12:59:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gaokao
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}