package com.sanelee.zhiyuan.Model;

public class GaoKao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.sid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.code
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.scid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.average
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer average;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.year
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.min
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer min;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.school_id
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer schoolId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.min_section
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer minSection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.max
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer max;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.local_province_name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String localProvinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.local_batch_name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String localBatchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.spname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String spname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.local_type_name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer localTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.rank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.proscore
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String proscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.areaname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.is985
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer is985;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.is211
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer is211;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.isDoubleFirstClass
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer isdoublefirstclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gaokao.type
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.sid
     *
     * @return the value of gaokao.sid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.sid
     *
     * @param sid the value for gaokao.sid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.code
     *
     * @return the value of gaokao.code
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.code
     *
     * @param code the value for gaokao.code
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.scid
     *
     * @return the value of gaokao.scid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.scid
     *
     * @param scid the value for gaokao.scid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.average
     *
     * @return the value of gaokao.average
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getAverage() {
        return average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.average
     *
     * @param average the value for gaokao.average
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setAverage(Integer average) {
        this.average = average;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.year
     *
     * @return the value of gaokao.year
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.year
     *
     * @param year the value for gaokao.year
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.min
     *
     * @return the value of gaokao.min
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getMin() {
        return min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.min
     *
     * @param min the value for gaokao.min
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setMin(Integer min) {
        this.min = min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.school_id
     *
     * @return the value of gaokao.school_id
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.school_id
     *
     * @param schoolId the value for gaokao.school_id
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.min_section
     *
     * @return the value of gaokao.min_section
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getMinSection() {
        return minSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.min_section
     *
     * @param minSection the value for gaokao.min_section
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setMinSection(Integer minSection) {
        this.minSection = minSection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.max
     *
     * @return the value of gaokao.max
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getMax() {
        return max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.max
     *
     * @param max the value for gaokao.max
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setMax(Integer max) {
        this.max = max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.local_province_name
     *
     * @return the value of gaokao.local_province_name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getLocalProvinceName() {
        return localProvinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.local_province_name
     *
     * @param localProvinceName the value for gaokao.local_province_name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setLocalProvinceName(String localProvinceName) {
        this.localProvinceName = localProvinceName == null ? null : localProvinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.local_batch_name
     *
     * @return the value of gaokao.local_batch_name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getLocalBatchName() {
        return localBatchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.local_batch_name
     *
     * @param localBatchName the value for gaokao.local_batch_name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setLocalBatchName(String localBatchName) {
        this.localBatchName = localBatchName == null ? null : localBatchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.spname
     *
     * @return the value of gaokao.spname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getSpname() {
        return spname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.spname
     *
     * @param spname the value for gaokao.spname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setSpname(String spname) {
        this.spname = spname == null ? null : spname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.name
     *
     * @return the value of gaokao.name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.name
     *
     * @param name the value for gaokao.name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.local_type_name
     *
     * @return the value of gaokao.local_type_name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getLocalTypeName() {
        return localTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.local_type_name
     *
     * @param localTypeName the value for gaokao.local_type_name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setLocalTypeName(Integer localTypeName) {
        this.localTypeName = localTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.rank
     *
     * @return the value of gaokao.rank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.rank
     *
     * @param rank the value for gaokao.rank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.proscore
     *
     * @return the value of gaokao.proscore
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getProscore() {
        return proscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.proscore
     *
     * @param proscore the value for gaokao.proscore
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setProscore(String proscore) {
        this.proscore = proscore == null ? null : proscore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.areaname
     *
     * @return the value of gaokao.areaname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.areaname
     *
     * @param areaname the value for gaokao.areaname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.is985
     *
     * @return the value of gaokao.is985
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getIs985() {
        return is985;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.is985
     *
     * @param is985 the value for gaokao.is985
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setIs985(Integer is985) {
        this.is985 = is985;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.is211
     *
     * @return the value of gaokao.is211
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getIs211() {
        return is211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.is211
     *
     * @param is211 the value for gaokao.is211
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setIs211(Integer is211) {
        this.is211 = is211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.isDoubleFirstClass
     *
     * @return the value of gaokao.isDoubleFirstClass
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getIsdoublefirstclass() {
        return isdoublefirstclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.isDoubleFirstClass
     *
     * @param isdoublefirstclass the value for gaokao.isDoubleFirstClass
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setIsdoublefirstclass(Integer isdoublefirstclass) {
        this.isdoublefirstclass = isdoublefirstclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gaokao.type
     *
     * @return the value of gaokao.type
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gaokao.type
     *
     * @param type the value for gaokao.type
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}