package com.sanelee.zhiyuan.Model;

public class Profession {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.pid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.subject
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.major
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.proname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String proname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.timelength
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String timelength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.classes
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String classes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.job
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.graduate
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String graduate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.code
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.sort
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.description
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.pid
     *
     * @return the value of profession.pid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.pid
     *
     * @param pid the value for profession.pid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.subject
     *
     * @return the value of profession.subject
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.subject
     *
     * @param subject the value for profession.subject
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.major
     *
     * @return the value of profession.major
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.major
     *
     * @param major the value for profession.major
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.proname
     *
     * @return the value of profession.proname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.proname
     *
     * @param proname the value for profession.proname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.timelength
     *
     * @return the value of profession.timelength
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getTimelength() {
        return timelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.timelength
     *
     * @param timelength the value for profession.timelength
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setTimelength(String timelength) {
        this.timelength = timelength == null ? null : timelength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.classes
     *
     * @return the value of profession.classes
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.classes
     *
     * @param classes the value for profession.classes
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setClasses(String classes) {
        this.classes = classes == null ? null : classes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.job
     *
     * @return the value of profession.job
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.job
     *
     * @param job the value for profession.job
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.graduate
     *
     * @return the value of profession.graduate
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getGraduate() {
        return graduate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.graduate
     *
     * @param graduate the value for profession.graduate
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setGraduate(String graduate) {
        this.graduate = graduate == null ? null : graduate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.code
     *
     * @return the value of profession.code
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.code
     *
     * @param code the value for profession.code
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.sort
     *
     * @return the value of profession.sort
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.sort
     *
     * @param sort the value for profession.sort
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.description
     *
     * @return the value of profession.description
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.description
     *
     * @param description the value for profession.description
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}