package com.sanelee.zhiyuan.Model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.value1
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer value1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.value2
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer value2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.item
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String item;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.value1
     *
     * @return the value of question.value1
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getValue1() {
        return value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.value1
     *
     * @param value1 the value for question.value1
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setValue1(Integer value1) {
        this.value1 = value1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.value2
     *
     * @return the value of question.value2
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getValue2() {
        return value2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.value2
     *
     * @param value2 the value for question.value2
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setValue2(Integer value2) {
        this.value2 = value2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.item
     *
     * @return the value of question.item
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getItem() {
        return item;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.item
     *
     * @param item the value for question.item
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setItem(String item) {
        this.item = item == null ? null : item.trim();
    }
}