package com.sanelee.zhiyuan.Model;

public class SchoolScore {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolscore.scid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolscore.sort
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolscore.name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolscore.minScore
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer minscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolscore.minRank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer minrank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolscore.batch
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer batch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schoolscore.year
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer year;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolscore.scid
     *
     * @return the value of schoolscore.scid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolscore.scid
     *
     * @param scid the value for schoolscore.scid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolscore.sort
     *
     * @return the value of schoolscore.sort
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolscore.sort
     *
     * @param sort the value for schoolscore.sort
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolscore.name
     *
     * @return the value of schoolscore.name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolscore.name
     *
     * @param name the value for schoolscore.name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolscore.minScore
     *
     * @return the value of schoolscore.minScore
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getMinscore() {
        return minscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolscore.minScore
     *
     * @param minscore the value for schoolscore.minScore
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setMinscore(Integer minscore) {
        this.minscore = minscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolscore.minRank
     *
     * @return the value of schoolscore.minRank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getMinrank() {
        return minrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolscore.minRank
     *
     * @param minrank the value for schoolscore.minRank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setMinrank(Integer minrank) {
        this.minrank = minrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolscore.batch
     *
     * @return the value of schoolscore.batch
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolscore.batch
     *
     * @param batch the value for schoolscore.batch
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setBatch(Integer batch) {
        this.batch = batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schoolscore.year
     *
     * @return the value of schoolscore.year
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schoolscore.year
     *
     * @param year the value for schoolscore.year
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setYear(Integer year) {
        this.year = year;
    }
}