package com.sanelee.zhiyuan.Model;

public class School {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.scid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer scid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.rank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.areaname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.areaid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.acronym
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String acronym;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.region
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.reid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer reid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.usedname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String usedname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.type
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.foundingYear
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer foundingyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.department
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.iscombine
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String iscombine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.is985
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer is985;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.is211
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer is211;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.isDoubleFirstClass
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer isdoublefirstclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.firstClassNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer firstclassnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.facultyNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer facultynum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.academicianNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer academiciannum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.changjiangScholarNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer changjiangscholarnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.teachersNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer teachersnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.undergraProNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer undergrapronum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.postgraProNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer postgrapronum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.doctorProNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer doctorpronum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.mainLabNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer mainlabnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.undergraEnrollNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer undergraenrollnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.postgraEnrollNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer postgraenrollnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.schoolWeb
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String schoolweb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column school.description
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.scid
     *
     * @return the value of school.scid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getScid() {
        return scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.scid
     *
     * @param scid the value for school.scid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setScid(Integer scid) {
        this.scid = scid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.rank
     *
     * @return the value of school.rank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.rank
     *
     * @param rank the value for school.rank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.name
     *
     * @return the value of school.name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.name
     *
     * @param name the value for school.name
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.areaname
     *
     * @return the value of school.areaname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.areaname
     *
     * @param areaname the value for school.areaname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.areaid
     *
     * @return the value of school.areaid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.areaid
     *
     * @param areaid the value for school.areaid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.acronym
     *
     * @return the value of school.acronym
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getAcronym() {
        return acronym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.acronym
     *
     * @param acronym the value for school.acronym
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setAcronym(String acronym) {
        this.acronym = acronym == null ? null : acronym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.region
     *
     * @return the value of school.region
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.region
     *
     * @param region the value for school.region
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.reid
     *
     * @return the value of school.reid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getReid() {
        return reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.reid
     *
     * @param reid the value for school.reid
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setReid(Integer reid) {
        this.reid = reid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.usedname
     *
     * @return the value of school.usedname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getUsedname() {
        return usedname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.usedname
     *
     * @param usedname the value for school.usedname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUsedname(String usedname) {
        this.usedname = usedname == null ? null : usedname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.type
     *
     * @return the value of school.type
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.type
     *
     * @param type the value for school.type
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.foundingYear
     *
     * @return the value of school.foundingYear
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getFoundingyear() {
        return foundingyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.foundingYear
     *
     * @param foundingyear the value for school.foundingYear
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setFoundingyear(Integer foundingyear) {
        this.foundingyear = foundingyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.department
     *
     * @return the value of school.department
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.department
     *
     * @param department the value for school.department
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.iscombine
     *
     * @return the value of school.iscombine
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getIscombine() {
        return iscombine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.iscombine
     *
     * @param iscombine the value for school.iscombine
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setIscombine(String iscombine) {
        this.iscombine = iscombine == null ? null : iscombine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.is985
     *
     * @return the value of school.is985
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getIs985() {
        return is985;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.is985
     *
     * @param is985 the value for school.is985
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setIs985(Integer is985) {
        this.is985 = is985;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.is211
     *
     * @return the value of school.is211
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getIs211() {
        return is211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.is211
     *
     * @param is211 the value for school.is211
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setIs211(Integer is211) {
        this.is211 = is211;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.isDoubleFirstClass
     *
     * @return the value of school.isDoubleFirstClass
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getIsdoublefirstclass() {
        return isdoublefirstclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.isDoubleFirstClass
     *
     * @param isdoublefirstclass the value for school.isDoubleFirstClass
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setIsdoublefirstclass(Integer isdoublefirstclass) {
        this.isdoublefirstclass = isdoublefirstclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.firstClassNum
     *
     * @return the value of school.firstClassNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getFirstclassnum() {
        return firstclassnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.firstClassNum
     *
     * @param firstclassnum the value for school.firstClassNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setFirstclassnum(Integer firstclassnum) {
        this.firstclassnum = firstclassnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.facultyNum
     *
     * @return the value of school.facultyNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getFacultynum() {
        return facultynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.facultyNum
     *
     * @param facultynum the value for school.facultyNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setFacultynum(Integer facultynum) {
        this.facultynum = facultynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.academicianNum
     *
     * @return the value of school.academicianNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getAcademiciannum() {
        return academiciannum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.academicianNum
     *
     * @param academiciannum the value for school.academicianNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setAcademiciannum(Integer academiciannum) {
        this.academiciannum = academiciannum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.changjiangScholarNum
     *
     * @return the value of school.changjiangScholarNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getChangjiangscholarnum() {
        return changjiangscholarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.changjiangScholarNum
     *
     * @param changjiangscholarnum the value for school.changjiangScholarNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setChangjiangscholarnum(Integer changjiangscholarnum) {
        this.changjiangscholarnum = changjiangscholarnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.teachersNum
     *
     * @return the value of school.teachersNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getTeachersnum() {
        return teachersnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.teachersNum
     *
     * @param teachersnum the value for school.teachersNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setTeachersnum(Integer teachersnum) {
        this.teachersnum = teachersnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.undergraProNum
     *
     * @return the value of school.undergraProNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getUndergrapronum() {
        return undergrapronum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.undergraProNum
     *
     * @param undergrapronum the value for school.undergraProNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUndergrapronum(Integer undergrapronum) {
        this.undergrapronum = undergrapronum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.postgraProNum
     *
     * @return the value of school.postgraProNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getPostgrapronum() {
        return postgrapronum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.postgraProNum
     *
     * @param postgrapronum the value for school.postgraProNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setPostgrapronum(Integer postgrapronum) {
        this.postgrapronum = postgrapronum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.doctorProNum
     *
     * @return the value of school.doctorProNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getDoctorpronum() {
        return doctorpronum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.doctorProNum
     *
     * @param doctorpronum the value for school.doctorProNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setDoctorpronum(Integer doctorpronum) {
        this.doctorpronum = doctorpronum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.mainLabNum
     *
     * @return the value of school.mainLabNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getMainlabnum() {
        return mainlabnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.mainLabNum
     *
     * @param mainlabnum the value for school.mainLabNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setMainlabnum(Integer mainlabnum) {
        this.mainlabnum = mainlabnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.undergraEnrollNum
     *
     * @return the value of school.undergraEnrollNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getUndergraenrollnum() {
        return undergraenrollnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.undergraEnrollNum
     *
     * @param undergraenrollnum the value for school.undergraEnrollNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUndergraenrollnum(Integer undergraenrollnum) {
        this.undergraenrollnum = undergraenrollnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.postgraEnrollNum
     *
     * @return the value of school.postgraEnrollNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getPostgraenrollnum() {
        return postgraenrollnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.postgraEnrollNum
     *
     * @param postgraenrollnum the value for school.postgraEnrollNum
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setPostgraenrollnum(Integer postgraenrollnum) {
        this.postgraenrollnum = postgraenrollnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.schoolWeb
     *
     * @return the value of school.schoolWeb
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getSchoolweb() {
        return schoolweb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.schoolWeb
     *
     * @param schoolweb the value for school.schoolWeb
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setSchoolweb(String schoolweb) {
        this.schoolweb = schoolweb == null ? null : schoolweb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column school.description
     *
     * @return the value of school.description
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column school.description
     *
     * @param description the value for school.description
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}