package com.sanelee.zhiyuan.Model;

import java.util.ArrayList;
import java.util.List;

public class SchoolExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public SchoolExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andScidIsNull() {
            addCriterion("scid is null");
            return (Criteria) this;
        }

        public Criteria andScidIsNotNull() {
            addCriterion("scid is not null");
            return (Criteria) this;
        }

        public Criteria andScidEqualTo(Integer value) {
            addCriterion("scid =", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotEqualTo(Integer value) {
            addCriterion("scid <>", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidGreaterThan(Integer value) {
            addCriterion("scid >", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidGreaterThanOrEqualTo(Integer value) {
            addCriterion("scid >=", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidLessThan(Integer value) {
            addCriterion("scid <", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidLessThanOrEqualTo(Integer value) {
            addCriterion("scid <=", value, "scid");
            return (Criteria) this;
        }

        public Criteria andScidIn(List<Integer> values) {
            addCriterion("scid in", values, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotIn(List<Integer> values) {
            addCriterion("scid not in", values, "scid");
            return (Criteria) this;
        }

        public Criteria andScidBetween(Integer value1, Integer value2) {
            addCriterion("scid between", value1, value2, "scid");
            return (Criteria) this;
        }

        public Criteria andScidNotBetween(Integer value1, Integer value2) {
            addCriterion("scid not between", value1, value2, "scid");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(Integer value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(Integer value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(Integer value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(Integer value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(Integer value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(Integer value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<Integer> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<Integer> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(Integer value1, Integer value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(Integer value1, Integer value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAreanameIsNull() {
            addCriterion("areaname is null");
            return (Criteria) this;
        }

        public Criteria andAreanameIsNotNull() {
            addCriterion("areaname is not null");
            return (Criteria) this;
        }

        public Criteria andAreanameEqualTo(String value) {
            addCriterion("areaname =", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameNotEqualTo(String value) {
            addCriterion("areaname <>", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameGreaterThan(String value) {
            addCriterion("areaname >", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameGreaterThanOrEqualTo(String value) {
            addCriterion("areaname >=", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameLessThan(String value) {
            addCriterion("areaname <", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameLessThanOrEqualTo(String value) {
            addCriterion("areaname <=", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameLike(String value) {
            addCriterion("areaname like", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameNotLike(String value) {
            addCriterion("areaname not like", value, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameIn(List<String> values) {
            addCriterion("areaname in", values, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameNotIn(List<String> values) {
            addCriterion("areaname not in", values, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameBetween(String value1, String value2) {
            addCriterion("areaname between", value1, value2, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreanameNotBetween(String value1, String value2) {
            addCriterion("areaname not between", value1, value2, "areaname");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNull() {
            addCriterion("areaid is null");
            return (Criteria) this;
        }

        public Criteria andAreaidIsNotNull() {
            addCriterion("areaid is not null");
            return (Criteria) this;
        }

        public Criteria andAreaidEqualTo(Integer value) {
            addCriterion("areaid =", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotEqualTo(Integer value) {
            addCriterion("areaid <>", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThan(Integer value) {
            addCriterion("areaid >", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidGreaterThanOrEqualTo(Integer value) {
            addCriterion("areaid >=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThan(Integer value) {
            addCriterion("areaid <", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidLessThanOrEqualTo(Integer value) {
            addCriterion("areaid <=", value, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidIn(List<Integer> values) {
            addCriterion("areaid in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotIn(List<Integer> values) {
            addCriterion("areaid not in", values, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidBetween(Integer value1, Integer value2) {
            addCriterion("areaid between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andAreaidNotBetween(Integer value1, Integer value2) {
            addCriterion("areaid not between", value1, value2, "areaid");
            return (Criteria) this;
        }

        public Criteria andAcronymIsNull() {
            addCriterion("acronym is null");
            return (Criteria) this;
        }

        public Criteria andAcronymIsNotNull() {
            addCriterion("acronym is not null");
            return (Criteria) this;
        }

        public Criteria andAcronymEqualTo(String value) {
            addCriterion("acronym =", value, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymNotEqualTo(String value) {
            addCriterion("acronym <>", value, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymGreaterThan(String value) {
            addCriterion("acronym >", value, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymGreaterThanOrEqualTo(String value) {
            addCriterion("acronym >=", value, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymLessThan(String value) {
            addCriterion("acronym <", value, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymLessThanOrEqualTo(String value) {
            addCriterion("acronym <=", value, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymLike(String value) {
            addCriterion("acronym like", value, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymNotLike(String value) {
            addCriterion("acronym not like", value, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymIn(List<String> values) {
            addCriterion("acronym in", values, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymNotIn(List<String> values) {
            addCriterion("acronym not in", values, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymBetween(String value1, String value2) {
            addCriterion("acronym between", value1, value2, "acronym");
            return (Criteria) this;
        }

        public Criteria andAcronymNotBetween(String value1, String value2) {
            addCriterion("acronym not between", value1, value2, "acronym");
            return (Criteria) this;
        }

        public Criteria andRegionIsNull() {
            addCriterion("region is null");
            return (Criteria) this;
        }

        public Criteria andRegionIsNotNull() {
            addCriterion("region is not null");
            return (Criteria) this;
        }

        public Criteria andRegionEqualTo(String value) {
            addCriterion("region =", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotEqualTo(String value) {
            addCriterion("region <>", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThan(String value) {
            addCriterion("region >", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionGreaterThanOrEqualTo(String value) {
            addCriterion("region >=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThan(String value) {
            addCriterion("region <", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLessThanOrEqualTo(String value) {
            addCriterion("region <=", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionLike(String value) {
            addCriterion("region like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotLike(String value) {
            addCriterion("region not like", value, "region");
            return (Criteria) this;
        }

        public Criteria andRegionIn(List<String> values) {
            addCriterion("region in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotIn(List<String> values) {
            addCriterion("region not in", values, "region");
            return (Criteria) this;
        }

        public Criteria andRegionBetween(String value1, String value2) {
            addCriterion("region between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andRegionNotBetween(String value1, String value2) {
            addCriterion("region not between", value1, value2, "region");
            return (Criteria) this;
        }

        public Criteria andReidIsNull() {
            addCriterion("reid is null");
            return (Criteria) this;
        }

        public Criteria andReidIsNotNull() {
            addCriterion("reid is not null");
            return (Criteria) this;
        }

        public Criteria andReidEqualTo(Integer value) {
            addCriterion("reid =", value, "reid");
            return (Criteria) this;
        }

        public Criteria andReidNotEqualTo(Integer value) {
            addCriterion("reid <>", value, "reid");
            return (Criteria) this;
        }

        public Criteria andReidGreaterThan(Integer value) {
            addCriterion("reid >", value, "reid");
            return (Criteria) this;
        }

        public Criteria andReidGreaterThanOrEqualTo(Integer value) {
            addCriterion("reid >=", value, "reid");
            return (Criteria) this;
        }

        public Criteria andReidLessThan(Integer value) {
            addCriterion("reid <", value, "reid");
            return (Criteria) this;
        }

        public Criteria andReidLessThanOrEqualTo(Integer value) {
            addCriterion("reid <=", value, "reid");
            return (Criteria) this;
        }

        public Criteria andReidIn(List<Integer> values) {
            addCriterion("reid in", values, "reid");
            return (Criteria) this;
        }

        public Criteria andReidNotIn(List<Integer> values) {
            addCriterion("reid not in", values, "reid");
            return (Criteria) this;
        }

        public Criteria andReidBetween(Integer value1, Integer value2) {
            addCriterion("reid between", value1, value2, "reid");
            return (Criteria) this;
        }

        public Criteria andReidNotBetween(Integer value1, Integer value2) {
            addCriterion("reid not between", value1, value2, "reid");
            return (Criteria) this;
        }

        public Criteria andUsednameIsNull() {
            addCriterion("usedname is null");
            return (Criteria) this;
        }

        public Criteria andUsednameIsNotNull() {
            addCriterion("usedname is not null");
            return (Criteria) this;
        }

        public Criteria andUsednameEqualTo(String value) {
            addCriterion("usedname =", value, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameNotEqualTo(String value) {
            addCriterion("usedname <>", value, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameGreaterThan(String value) {
            addCriterion("usedname >", value, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameGreaterThanOrEqualTo(String value) {
            addCriterion("usedname >=", value, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameLessThan(String value) {
            addCriterion("usedname <", value, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameLessThanOrEqualTo(String value) {
            addCriterion("usedname <=", value, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameLike(String value) {
            addCriterion("usedname like", value, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameNotLike(String value) {
            addCriterion("usedname not like", value, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameIn(List<String> values) {
            addCriterion("usedname in", values, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameNotIn(List<String> values) {
            addCriterion("usedname not in", values, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameBetween(String value1, String value2) {
            addCriterion("usedname between", value1, value2, "usedname");
            return (Criteria) this;
        }

        public Criteria andUsednameNotBetween(String value1, String value2) {
            addCriterion("usedname not between", value1, value2, "usedname");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andFoundingyearIsNull() {
            addCriterion("foundingYear is null");
            return (Criteria) this;
        }

        public Criteria andFoundingyearIsNotNull() {
            addCriterion("foundingYear is not null");
            return (Criteria) this;
        }

        public Criteria andFoundingyearEqualTo(Integer value) {
            addCriterion("foundingYear =", value, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andFoundingyearNotEqualTo(Integer value) {
            addCriterion("foundingYear <>", value, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andFoundingyearGreaterThan(Integer value) {
            addCriterion("foundingYear >", value, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andFoundingyearGreaterThanOrEqualTo(Integer value) {
            addCriterion("foundingYear >=", value, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andFoundingyearLessThan(Integer value) {
            addCriterion("foundingYear <", value, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andFoundingyearLessThanOrEqualTo(Integer value) {
            addCriterion("foundingYear <=", value, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andFoundingyearIn(List<Integer> values) {
            addCriterion("foundingYear in", values, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andFoundingyearNotIn(List<Integer> values) {
            addCriterion("foundingYear not in", values, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andFoundingyearBetween(Integer value1, Integer value2) {
            addCriterion("foundingYear between", value1, value2, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andFoundingyearNotBetween(Integer value1, Integer value2) {
            addCriterion("foundingYear not between", value1, value2, "foundingyear");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNull() {
            addCriterion("department is null");
            return (Criteria) this;
        }

        public Criteria andDepartmentIsNotNull() {
            addCriterion("department is not null");
            return (Criteria) this;
        }

        public Criteria andDepartmentEqualTo(String value) {
            addCriterion("department =", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotEqualTo(String value) {
            addCriterion("department <>", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThan(String value) {
            addCriterion("department >", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("department >=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThan(String value) {
            addCriterion("department <", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLessThanOrEqualTo(String value) {
            addCriterion("department <=", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentLike(String value) {
            addCriterion("department like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotLike(String value) {
            addCriterion("department not like", value, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentIn(List<String> values) {
            addCriterion("department in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotIn(List<String> values) {
            addCriterion("department not in", values, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentBetween(String value1, String value2) {
            addCriterion("department between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andDepartmentNotBetween(String value1, String value2) {
            addCriterion("department not between", value1, value2, "department");
            return (Criteria) this;
        }

        public Criteria andIscombineIsNull() {
            addCriterion("iscombine is null");
            return (Criteria) this;
        }

        public Criteria andIscombineIsNotNull() {
            addCriterion("iscombine is not null");
            return (Criteria) this;
        }

        public Criteria andIscombineEqualTo(String value) {
            addCriterion("iscombine =", value, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineNotEqualTo(String value) {
            addCriterion("iscombine <>", value, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineGreaterThan(String value) {
            addCriterion("iscombine >", value, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineGreaterThanOrEqualTo(String value) {
            addCriterion("iscombine >=", value, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineLessThan(String value) {
            addCriterion("iscombine <", value, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineLessThanOrEqualTo(String value) {
            addCriterion("iscombine <=", value, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineLike(String value) {
            addCriterion("iscombine like", value, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineNotLike(String value) {
            addCriterion("iscombine not like", value, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineIn(List<String> values) {
            addCriterion("iscombine in", values, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineNotIn(List<String> values) {
            addCriterion("iscombine not in", values, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineBetween(String value1, String value2) {
            addCriterion("iscombine between", value1, value2, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIscombineNotBetween(String value1, String value2) {
            addCriterion("iscombine not between", value1, value2, "iscombine");
            return (Criteria) this;
        }

        public Criteria andIs985IsNull() {
            addCriterion("is985 is null");
            return (Criteria) this;
        }

        public Criteria andIs985IsNotNull() {
            addCriterion("is985 is not null");
            return (Criteria) this;
        }

        public Criteria andIs985EqualTo(Integer value) {
            addCriterion("is985 =", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985NotEqualTo(Integer value) {
            addCriterion("is985 <>", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985GreaterThan(Integer value) {
            addCriterion("is985 >", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985GreaterThanOrEqualTo(Integer value) {
            addCriterion("is985 >=", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985LessThan(Integer value) {
            addCriterion("is985 <", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985LessThanOrEqualTo(Integer value) {
            addCriterion("is985 <=", value, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985In(List<Integer> values) {
            addCriterion("is985 in", values, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985NotIn(List<Integer> values) {
            addCriterion("is985 not in", values, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985Between(Integer value1, Integer value2) {
            addCriterion("is985 between", value1, value2, "is985");
            return (Criteria) this;
        }

        public Criteria andIs985NotBetween(Integer value1, Integer value2) {
            addCriterion("is985 not between", value1, value2, "is985");
            return (Criteria) this;
        }

        public Criteria andIs211IsNull() {
            addCriterion("is211 is null");
            return (Criteria) this;
        }

        public Criteria andIs211IsNotNull() {
            addCriterion("is211 is not null");
            return (Criteria) this;
        }

        public Criteria andIs211EqualTo(Integer value) {
            addCriterion("is211 =", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211NotEqualTo(Integer value) {
            addCriterion("is211 <>", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211GreaterThan(Integer value) {
            addCriterion("is211 >", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211GreaterThanOrEqualTo(Integer value) {
            addCriterion("is211 >=", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211LessThan(Integer value) {
            addCriterion("is211 <", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211LessThanOrEqualTo(Integer value) {
            addCriterion("is211 <=", value, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211In(List<Integer> values) {
            addCriterion("is211 in", values, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211NotIn(List<Integer> values) {
            addCriterion("is211 not in", values, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211Between(Integer value1, Integer value2) {
            addCriterion("is211 between", value1, value2, "is211");
            return (Criteria) this;
        }

        public Criteria andIs211NotBetween(Integer value1, Integer value2) {
            addCriterion("is211 not between", value1, value2, "is211");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassIsNull() {
            addCriterion("isDoubleFirstClass is null");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassIsNotNull() {
            addCriterion("isDoubleFirstClass is not null");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassEqualTo(Integer value) {
            addCriterion("isDoubleFirstClass =", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassNotEqualTo(Integer value) {
            addCriterion("isDoubleFirstClass <>", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassGreaterThan(Integer value) {
            addCriterion("isDoubleFirstClass >", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDoubleFirstClass >=", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassLessThan(Integer value) {
            addCriterion("isDoubleFirstClass <", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassLessThanOrEqualTo(Integer value) {
            addCriterion("isDoubleFirstClass <=", value, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassIn(List<Integer> values) {
            addCriterion("isDoubleFirstClass in", values, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassNotIn(List<Integer> values) {
            addCriterion("isDoubleFirstClass not in", values, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassBetween(Integer value1, Integer value2) {
            addCriterion("isDoubleFirstClass between", value1, value2, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andIsdoublefirstclassNotBetween(Integer value1, Integer value2) {
            addCriterion("isDoubleFirstClass not between", value1, value2, "isdoublefirstclass");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumIsNull() {
            addCriterion("firstClassNum is null");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumIsNotNull() {
            addCriterion("firstClassNum is not null");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumEqualTo(Integer value) {
            addCriterion("firstClassNum =", value, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumNotEqualTo(Integer value) {
            addCriterion("firstClassNum <>", value, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumGreaterThan(Integer value) {
            addCriterion("firstClassNum >", value, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("firstClassNum >=", value, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumLessThan(Integer value) {
            addCriterion("firstClassNum <", value, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumLessThanOrEqualTo(Integer value) {
            addCriterion("firstClassNum <=", value, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumIn(List<Integer> values) {
            addCriterion("firstClassNum in", values, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumNotIn(List<Integer> values) {
            addCriterion("firstClassNum not in", values, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumBetween(Integer value1, Integer value2) {
            addCriterion("firstClassNum between", value1, value2, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFirstclassnumNotBetween(Integer value1, Integer value2) {
            addCriterion("firstClassNum not between", value1, value2, "firstclassnum");
            return (Criteria) this;
        }

        public Criteria andFacultynumIsNull() {
            addCriterion("facultyNum is null");
            return (Criteria) this;
        }

        public Criteria andFacultynumIsNotNull() {
            addCriterion("facultyNum is not null");
            return (Criteria) this;
        }

        public Criteria andFacultynumEqualTo(Integer value) {
            addCriterion("facultyNum =", value, "facultynum");
            return (Criteria) this;
        }

        public Criteria andFacultynumNotEqualTo(Integer value) {
            addCriterion("facultyNum <>", value, "facultynum");
            return (Criteria) this;
        }

        public Criteria andFacultynumGreaterThan(Integer value) {
            addCriterion("facultyNum >", value, "facultynum");
            return (Criteria) this;
        }

        public Criteria andFacultynumGreaterThanOrEqualTo(Integer value) {
            addCriterion("facultyNum >=", value, "facultynum");
            return (Criteria) this;
        }

        public Criteria andFacultynumLessThan(Integer value) {
            addCriterion("facultyNum <", value, "facultynum");
            return (Criteria) this;
        }

        public Criteria andFacultynumLessThanOrEqualTo(Integer value) {
            addCriterion("facultyNum <=", value, "facultynum");
            return (Criteria) this;
        }

        public Criteria andFacultynumIn(List<Integer> values) {
            addCriterion("facultyNum in", values, "facultynum");
            return (Criteria) this;
        }

        public Criteria andFacultynumNotIn(List<Integer> values) {
            addCriterion("facultyNum not in", values, "facultynum");
            return (Criteria) this;
        }

        public Criteria andFacultynumBetween(Integer value1, Integer value2) {
            addCriterion("facultyNum between", value1, value2, "facultynum");
            return (Criteria) this;
        }

        public Criteria andFacultynumNotBetween(Integer value1, Integer value2) {
            addCriterion("facultyNum not between", value1, value2, "facultynum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumIsNull() {
            addCriterion("academicianNum is null");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumIsNotNull() {
            addCriterion("academicianNum is not null");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumEqualTo(Integer value) {
            addCriterion("academicianNum =", value, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumNotEqualTo(Integer value) {
            addCriterion("academicianNum <>", value, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumGreaterThan(Integer value) {
            addCriterion("academicianNum >", value, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumGreaterThanOrEqualTo(Integer value) {
            addCriterion("academicianNum >=", value, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumLessThan(Integer value) {
            addCriterion("academicianNum <", value, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumLessThanOrEqualTo(Integer value) {
            addCriterion("academicianNum <=", value, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumIn(List<Integer> values) {
            addCriterion("academicianNum in", values, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumNotIn(List<Integer> values) {
            addCriterion("academicianNum not in", values, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumBetween(Integer value1, Integer value2) {
            addCriterion("academicianNum between", value1, value2, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andAcademiciannumNotBetween(Integer value1, Integer value2) {
            addCriterion("academicianNum not between", value1, value2, "academiciannum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumIsNull() {
            addCriterion("changjiangScholarNum is null");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumIsNotNull() {
            addCriterion("changjiangScholarNum is not null");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumEqualTo(Integer value) {
            addCriterion("changjiangScholarNum =", value, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumNotEqualTo(Integer value) {
            addCriterion("changjiangScholarNum <>", value, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumGreaterThan(Integer value) {
            addCriterion("changjiangScholarNum >", value, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("changjiangScholarNum >=", value, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumLessThan(Integer value) {
            addCriterion("changjiangScholarNum <", value, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumLessThanOrEqualTo(Integer value) {
            addCriterion("changjiangScholarNum <=", value, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumIn(List<Integer> values) {
            addCriterion("changjiangScholarNum in", values, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumNotIn(List<Integer> values) {
            addCriterion("changjiangScholarNum not in", values, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumBetween(Integer value1, Integer value2) {
            addCriterion("changjiangScholarNum between", value1, value2, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andChangjiangscholarnumNotBetween(Integer value1, Integer value2) {
            addCriterion("changjiangScholarNum not between", value1, value2, "changjiangscholarnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumIsNull() {
            addCriterion("teachersNum is null");
            return (Criteria) this;
        }

        public Criteria andTeachersnumIsNotNull() {
            addCriterion("teachersNum is not null");
            return (Criteria) this;
        }

        public Criteria andTeachersnumEqualTo(Integer value) {
            addCriterion("teachersNum =", value, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumNotEqualTo(Integer value) {
            addCriterion("teachersNum <>", value, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumGreaterThan(Integer value) {
            addCriterion("teachersNum >", value, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("teachersNum >=", value, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumLessThan(Integer value) {
            addCriterion("teachersNum <", value, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumLessThanOrEqualTo(Integer value) {
            addCriterion("teachersNum <=", value, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumIn(List<Integer> values) {
            addCriterion("teachersNum in", values, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumNotIn(List<Integer> values) {
            addCriterion("teachersNum not in", values, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumBetween(Integer value1, Integer value2) {
            addCriterion("teachersNum between", value1, value2, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andTeachersnumNotBetween(Integer value1, Integer value2) {
            addCriterion("teachersNum not between", value1, value2, "teachersnum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumIsNull() {
            addCriterion("undergraProNum is null");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumIsNotNull() {
            addCriterion("undergraProNum is not null");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumEqualTo(Integer value) {
            addCriterion("undergraProNum =", value, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumNotEqualTo(Integer value) {
            addCriterion("undergraProNum <>", value, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumGreaterThan(Integer value) {
            addCriterion("undergraProNum >", value, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumGreaterThanOrEqualTo(Integer value) {
            addCriterion("undergraProNum >=", value, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumLessThan(Integer value) {
            addCriterion("undergraProNum <", value, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumLessThanOrEqualTo(Integer value) {
            addCriterion("undergraProNum <=", value, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumIn(List<Integer> values) {
            addCriterion("undergraProNum in", values, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumNotIn(List<Integer> values) {
            addCriterion("undergraProNum not in", values, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumBetween(Integer value1, Integer value2) {
            addCriterion("undergraProNum between", value1, value2, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andUndergrapronumNotBetween(Integer value1, Integer value2) {
            addCriterion("undergraProNum not between", value1, value2, "undergrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumIsNull() {
            addCriterion("postgraProNum is null");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumIsNotNull() {
            addCriterion("postgraProNum is not null");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumEqualTo(Integer value) {
            addCriterion("postgraProNum =", value, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumNotEqualTo(Integer value) {
            addCriterion("postgraProNum <>", value, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumGreaterThan(Integer value) {
            addCriterion("postgraProNum >", value, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumGreaterThanOrEqualTo(Integer value) {
            addCriterion("postgraProNum >=", value, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumLessThan(Integer value) {
            addCriterion("postgraProNum <", value, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumLessThanOrEqualTo(Integer value) {
            addCriterion("postgraProNum <=", value, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumIn(List<Integer> values) {
            addCriterion("postgraProNum in", values, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumNotIn(List<Integer> values) {
            addCriterion("postgraProNum not in", values, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumBetween(Integer value1, Integer value2) {
            addCriterion("postgraProNum between", value1, value2, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andPostgrapronumNotBetween(Integer value1, Integer value2) {
            addCriterion("postgraProNum not between", value1, value2, "postgrapronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumIsNull() {
            addCriterion("doctorProNum is null");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumIsNotNull() {
            addCriterion("doctorProNum is not null");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumEqualTo(Integer value) {
            addCriterion("doctorProNum =", value, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumNotEqualTo(Integer value) {
            addCriterion("doctorProNum <>", value, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumGreaterThan(Integer value) {
            addCriterion("doctorProNum >", value, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumGreaterThanOrEqualTo(Integer value) {
            addCriterion("doctorProNum >=", value, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumLessThan(Integer value) {
            addCriterion("doctorProNum <", value, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumLessThanOrEqualTo(Integer value) {
            addCriterion("doctorProNum <=", value, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumIn(List<Integer> values) {
            addCriterion("doctorProNum in", values, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumNotIn(List<Integer> values) {
            addCriterion("doctorProNum not in", values, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumBetween(Integer value1, Integer value2) {
            addCriterion("doctorProNum between", value1, value2, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andDoctorpronumNotBetween(Integer value1, Integer value2) {
            addCriterion("doctorProNum not between", value1, value2, "doctorpronum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumIsNull() {
            addCriterion("mainLabNum is null");
            return (Criteria) this;
        }

        public Criteria andMainlabnumIsNotNull() {
            addCriterion("mainLabNum is not null");
            return (Criteria) this;
        }

        public Criteria andMainlabnumEqualTo(Integer value) {
            addCriterion("mainLabNum =", value, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumNotEqualTo(Integer value) {
            addCriterion("mainLabNum <>", value, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumGreaterThan(Integer value) {
            addCriterion("mainLabNum >", value, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("mainLabNum >=", value, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumLessThan(Integer value) {
            addCriterion("mainLabNum <", value, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumLessThanOrEqualTo(Integer value) {
            addCriterion("mainLabNum <=", value, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumIn(List<Integer> values) {
            addCriterion("mainLabNum in", values, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumNotIn(List<Integer> values) {
            addCriterion("mainLabNum not in", values, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumBetween(Integer value1, Integer value2) {
            addCriterion("mainLabNum between", value1, value2, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andMainlabnumNotBetween(Integer value1, Integer value2) {
            addCriterion("mainLabNum not between", value1, value2, "mainlabnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumIsNull() {
            addCriterion("undergraEnrollNum is null");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumIsNotNull() {
            addCriterion("undergraEnrollNum is not null");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumEqualTo(Integer value) {
            addCriterion("undergraEnrollNum =", value, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumNotEqualTo(Integer value) {
            addCriterion("undergraEnrollNum <>", value, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumGreaterThan(Integer value) {
            addCriterion("undergraEnrollNum >", value, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("undergraEnrollNum >=", value, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumLessThan(Integer value) {
            addCriterion("undergraEnrollNum <", value, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumLessThanOrEqualTo(Integer value) {
            addCriterion("undergraEnrollNum <=", value, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumIn(List<Integer> values) {
            addCriterion("undergraEnrollNum in", values, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumNotIn(List<Integer> values) {
            addCriterion("undergraEnrollNum not in", values, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumBetween(Integer value1, Integer value2) {
            addCriterion("undergraEnrollNum between", value1, value2, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andUndergraenrollnumNotBetween(Integer value1, Integer value2) {
            addCriterion("undergraEnrollNum not between", value1, value2, "undergraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumIsNull() {
            addCriterion("postgraEnrollNum is null");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumIsNotNull() {
            addCriterion("postgraEnrollNum is not null");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumEqualTo(Integer value) {
            addCriterion("postgraEnrollNum =", value, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumNotEqualTo(Integer value) {
            addCriterion("postgraEnrollNum <>", value, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumGreaterThan(Integer value) {
            addCriterion("postgraEnrollNum >", value, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("postgraEnrollNum >=", value, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumLessThan(Integer value) {
            addCriterion("postgraEnrollNum <", value, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumLessThanOrEqualTo(Integer value) {
            addCriterion("postgraEnrollNum <=", value, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumIn(List<Integer> values) {
            addCriterion("postgraEnrollNum in", values, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumNotIn(List<Integer> values) {
            addCriterion("postgraEnrollNum not in", values, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumBetween(Integer value1, Integer value2) {
            addCriterion("postgraEnrollNum between", value1, value2, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andPostgraenrollnumNotBetween(Integer value1, Integer value2) {
            addCriterion("postgraEnrollNum not between", value1, value2, "postgraenrollnum");
            return (Criteria) this;
        }

        public Criteria andSchoolwebIsNull() {
            addCriterion("schoolWeb is null");
            return (Criteria) this;
        }

        public Criteria andSchoolwebIsNotNull() {
            addCriterion("schoolWeb is not null");
            return (Criteria) this;
        }

        public Criteria andSchoolwebEqualTo(String value) {
            addCriterion("schoolWeb =", value, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebNotEqualTo(String value) {
            addCriterion("schoolWeb <>", value, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebGreaterThan(String value) {
            addCriterion("schoolWeb >", value, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebGreaterThanOrEqualTo(String value) {
            addCriterion("schoolWeb >=", value, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebLessThan(String value) {
            addCriterion("schoolWeb <", value, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebLessThanOrEqualTo(String value) {
            addCriterion("schoolWeb <=", value, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebLike(String value) {
            addCriterion("schoolWeb like", value, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebNotLike(String value) {
            addCriterion("schoolWeb not like", value, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebIn(List<String> values) {
            addCriterion("schoolWeb in", values, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebNotIn(List<String> values) {
            addCriterion("schoolWeb not in", values, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebBetween(String value1, String value2) {
            addCriterion("schoolWeb between", value1, value2, "schoolweb");
            return (Criteria) this;
        }

        public Criteria andSchoolwebNotBetween(String value1, String value2) {
            addCriterion("schoolWeb not between", value1, value2, "schoolweb");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 20 12:59:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}