package com.sanelee.zhiyuan.Model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userName
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.passWord
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userRealname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String userrealname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usergender
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String usergender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userphone
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String userphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userwechat
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String userwechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userscore
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer userscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userarea
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String userarea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usersort
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String usersort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userrank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer userrank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.admin
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.token
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.vip
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    private Integer vip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userName
     *
     * @return the value of user.userName
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userName
     *
     * @param username the value for user.userName
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.passWord
     *
     * @return the value of user.passWord
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.passWord
     *
     * @param password the value for user.passWord
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userRealname
     *
     * @return the value of user.userRealname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getUserrealname() {
        return userrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userRealname
     *
     * @param userrealname the value for user.userRealname
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUserrealname(String userrealname) {
        this.userrealname = userrealname == null ? null : userrealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usergender
     *
     * @return the value of user.usergender
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getUsergender() {
        return usergender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usergender
     *
     * @param usergender the value for user.usergender
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUsergender(String usergender) {
        this.usergender = usergender == null ? null : usergender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userphone
     *
     * @return the value of user.userphone
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getUserphone() {
        return userphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userphone
     *
     * @param userphone the value for user.userphone
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUserphone(String userphone) {
        this.userphone = userphone == null ? null : userphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userwechat
     *
     * @return the value of user.userwechat
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getUserwechat() {
        return userwechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userwechat
     *
     * @param userwechat the value for user.userwechat
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUserwechat(String userwechat) {
        this.userwechat = userwechat == null ? null : userwechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userscore
     *
     * @return the value of user.userscore
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getUserscore() {
        return userscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userscore
     *
     * @param userscore the value for user.userscore
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUserscore(Integer userscore) {
        this.userscore = userscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userarea
     *
     * @return the value of user.userarea
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getUserarea() {
        return userarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userarea
     *
     * @param userarea the value for user.userarea
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUserarea(String userarea) {
        this.userarea = userarea == null ? null : userarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usersort
     *
     * @return the value of user.usersort
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getUsersort() {
        return usersort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usersort
     *
     * @param usersort the value for user.usersort
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUsersort(String usersort) {
        this.usersort = usersort == null ? null : usersort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userrank
     *
     * @return the value of user.userrank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getUserrank() {
        return userrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userrank
     *
     * @param userrank the value for user.userrank
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setUserrank(Integer userrank) {
        this.userrank = userrank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.admin
     *
     * @return the value of user.admin
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.admin
     *
     * @param admin the value for user.admin
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setAdmin(Integer admin) {
        this.admin = admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.token
     *
     * @return the value of user.token
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.token
     *
     * @param token the value for user.token
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.vip
     *
     * @return the value of user.vip
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Integer getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.vip
     *
     * @param vip the value for user.vip
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setVip(Integer vip) {
        this.vip = vip;
    }
}