package com.sanelee.zhiyuan.Model;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public UserExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("userName is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("userName is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("userName =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("userName <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("userName >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("userName <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("userName like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("userName not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("userName in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("userName not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("passWord is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("passWord is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("passWord =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("passWord <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("passWord >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("passWord >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("passWord <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("passWord <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("passWord like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("passWord not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("passWord in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("passWord not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("passWord between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("passWord not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andUserrealnameIsNull() {
            addCriterion("userRealname is null");
            return (Criteria) this;
        }

        public Criteria andUserrealnameIsNotNull() {
            addCriterion("userRealname is not null");
            return (Criteria) this;
        }

        public Criteria andUserrealnameEqualTo(String value) {
            addCriterion("userRealname =", value, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameNotEqualTo(String value) {
            addCriterion("userRealname <>", value, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameGreaterThan(String value) {
            addCriterion("userRealname >", value, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameGreaterThanOrEqualTo(String value) {
            addCriterion("userRealname >=", value, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameLessThan(String value) {
            addCriterion("userRealname <", value, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameLessThanOrEqualTo(String value) {
            addCriterion("userRealname <=", value, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameLike(String value) {
            addCriterion("userRealname like", value, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameNotLike(String value) {
            addCriterion("userRealname not like", value, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameIn(List<String> values) {
            addCriterion("userRealname in", values, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameNotIn(List<String> values) {
            addCriterion("userRealname not in", values, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameBetween(String value1, String value2) {
            addCriterion("userRealname between", value1, value2, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUserrealnameNotBetween(String value1, String value2) {
            addCriterion("userRealname not between", value1, value2, "userrealname");
            return (Criteria) this;
        }

        public Criteria andUsergenderIsNull() {
            addCriterion("usergender is null");
            return (Criteria) this;
        }

        public Criteria andUsergenderIsNotNull() {
            addCriterion("usergender is not null");
            return (Criteria) this;
        }

        public Criteria andUsergenderEqualTo(String value) {
            addCriterion("usergender =", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderNotEqualTo(String value) {
            addCriterion("usergender <>", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderGreaterThan(String value) {
            addCriterion("usergender >", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderGreaterThanOrEqualTo(String value) {
            addCriterion("usergender >=", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderLessThan(String value) {
            addCriterion("usergender <", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderLessThanOrEqualTo(String value) {
            addCriterion("usergender <=", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderLike(String value) {
            addCriterion("usergender like", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderNotLike(String value) {
            addCriterion("usergender not like", value, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderIn(List<String> values) {
            addCriterion("usergender in", values, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderNotIn(List<String> values) {
            addCriterion("usergender not in", values, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderBetween(String value1, String value2) {
            addCriterion("usergender between", value1, value2, "usergender");
            return (Criteria) this;
        }

        public Criteria andUsergenderNotBetween(String value1, String value2) {
            addCriterion("usergender not between", value1, value2, "usergender");
            return (Criteria) this;
        }

        public Criteria andUserphoneIsNull() {
            addCriterion("userphone is null");
            return (Criteria) this;
        }

        public Criteria andUserphoneIsNotNull() {
            addCriterion("userphone is not null");
            return (Criteria) this;
        }

        public Criteria andUserphoneEqualTo(String value) {
            addCriterion("userphone =", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotEqualTo(String value) {
            addCriterion("userphone <>", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneGreaterThan(String value) {
            addCriterion("userphone >", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneGreaterThanOrEqualTo(String value) {
            addCriterion("userphone >=", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneLessThan(String value) {
            addCriterion("userphone <", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneLessThanOrEqualTo(String value) {
            addCriterion("userphone <=", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneLike(String value) {
            addCriterion("userphone like", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotLike(String value) {
            addCriterion("userphone not like", value, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneIn(List<String> values) {
            addCriterion("userphone in", values, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotIn(List<String> values) {
            addCriterion("userphone not in", values, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneBetween(String value1, String value2) {
            addCriterion("userphone between", value1, value2, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserphoneNotBetween(String value1, String value2) {
            addCriterion("userphone not between", value1, value2, "userphone");
            return (Criteria) this;
        }

        public Criteria andUserwechatIsNull() {
            addCriterion("userwechat is null");
            return (Criteria) this;
        }

        public Criteria andUserwechatIsNotNull() {
            addCriterion("userwechat is not null");
            return (Criteria) this;
        }

        public Criteria andUserwechatEqualTo(String value) {
            addCriterion("userwechat =", value, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatNotEqualTo(String value) {
            addCriterion("userwechat <>", value, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatGreaterThan(String value) {
            addCriterion("userwechat >", value, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatGreaterThanOrEqualTo(String value) {
            addCriterion("userwechat >=", value, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatLessThan(String value) {
            addCriterion("userwechat <", value, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatLessThanOrEqualTo(String value) {
            addCriterion("userwechat <=", value, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatLike(String value) {
            addCriterion("userwechat like", value, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatNotLike(String value) {
            addCriterion("userwechat not like", value, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatIn(List<String> values) {
            addCriterion("userwechat in", values, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatNotIn(List<String> values) {
            addCriterion("userwechat not in", values, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatBetween(String value1, String value2) {
            addCriterion("userwechat between", value1, value2, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserwechatNotBetween(String value1, String value2) {
            addCriterion("userwechat not between", value1, value2, "userwechat");
            return (Criteria) this;
        }

        public Criteria andUserscoreIsNull() {
            addCriterion("userscore is null");
            return (Criteria) this;
        }

        public Criteria andUserscoreIsNotNull() {
            addCriterion("userscore is not null");
            return (Criteria) this;
        }

        public Criteria andUserscoreEqualTo(Integer value) {
            addCriterion("userscore =", value, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserscoreNotEqualTo(Integer value) {
            addCriterion("userscore <>", value, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserscoreGreaterThan(Integer value) {
            addCriterion("userscore >", value, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserscoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("userscore >=", value, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserscoreLessThan(Integer value) {
            addCriterion("userscore <", value, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserscoreLessThanOrEqualTo(Integer value) {
            addCriterion("userscore <=", value, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserscoreIn(List<Integer> values) {
            addCriterion("userscore in", values, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserscoreNotIn(List<Integer> values) {
            addCriterion("userscore not in", values, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserscoreBetween(Integer value1, Integer value2) {
            addCriterion("userscore between", value1, value2, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserscoreNotBetween(Integer value1, Integer value2) {
            addCriterion("userscore not between", value1, value2, "userscore");
            return (Criteria) this;
        }

        public Criteria andUserareaIsNull() {
            addCriterion("userarea is null");
            return (Criteria) this;
        }

        public Criteria andUserareaIsNotNull() {
            addCriterion("userarea is not null");
            return (Criteria) this;
        }

        public Criteria andUserareaEqualTo(String value) {
            addCriterion("userarea =", value, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaNotEqualTo(String value) {
            addCriterion("userarea <>", value, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaGreaterThan(String value) {
            addCriterion("userarea >", value, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaGreaterThanOrEqualTo(String value) {
            addCriterion("userarea >=", value, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaLessThan(String value) {
            addCriterion("userarea <", value, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaLessThanOrEqualTo(String value) {
            addCriterion("userarea <=", value, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaLike(String value) {
            addCriterion("userarea like", value, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaNotLike(String value) {
            addCriterion("userarea not like", value, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaIn(List<String> values) {
            addCriterion("userarea in", values, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaNotIn(List<String> values) {
            addCriterion("userarea not in", values, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaBetween(String value1, String value2) {
            addCriterion("userarea between", value1, value2, "userarea");
            return (Criteria) this;
        }

        public Criteria andUserareaNotBetween(String value1, String value2) {
            addCriterion("userarea not between", value1, value2, "userarea");
            return (Criteria) this;
        }

        public Criteria andUsersortIsNull() {
            addCriterion("usersort is null");
            return (Criteria) this;
        }

        public Criteria andUsersortIsNotNull() {
            addCriterion("usersort is not null");
            return (Criteria) this;
        }

        public Criteria andUsersortEqualTo(String value) {
            addCriterion("usersort =", value, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortNotEqualTo(String value) {
            addCriterion("usersort <>", value, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortGreaterThan(String value) {
            addCriterion("usersort >", value, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortGreaterThanOrEqualTo(String value) {
            addCriterion("usersort >=", value, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortLessThan(String value) {
            addCriterion("usersort <", value, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortLessThanOrEqualTo(String value) {
            addCriterion("usersort <=", value, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortLike(String value) {
            addCriterion("usersort like", value, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortNotLike(String value) {
            addCriterion("usersort not like", value, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortIn(List<String> values) {
            addCriterion("usersort in", values, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortNotIn(List<String> values) {
            addCriterion("usersort not in", values, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortBetween(String value1, String value2) {
            addCriterion("usersort between", value1, value2, "usersort");
            return (Criteria) this;
        }

        public Criteria andUsersortNotBetween(String value1, String value2) {
            addCriterion("usersort not between", value1, value2, "usersort");
            return (Criteria) this;
        }

        public Criteria andUserrankIsNull() {
            addCriterion("userrank is null");
            return (Criteria) this;
        }

        public Criteria andUserrankIsNotNull() {
            addCriterion("userrank is not null");
            return (Criteria) this;
        }

        public Criteria andUserrankEqualTo(Integer value) {
            addCriterion("userrank =", value, "userrank");
            return (Criteria) this;
        }

        public Criteria andUserrankNotEqualTo(Integer value) {
            addCriterion("userrank <>", value, "userrank");
            return (Criteria) this;
        }

        public Criteria andUserrankGreaterThan(Integer value) {
            addCriterion("userrank >", value, "userrank");
            return (Criteria) this;
        }

        public Criteria andUserrankGreaterThanOrEqualTo(Integer value) {
            addCriterion("userrank >=", value, "userrank");
            return (Criteria) this;
        }

        public Criteria andUserrankLessThan(Integer value) {
            addCriterion("userrank <", value, "userrank");
            return (Criteria) this;
        }

        public Criteria andUserrankLessThanOrEqualTo(Integer value) {
            addCriterion("userrank <=", value, "userrank");
            return (Criteria) this;
        }

        public Criteria andUserrankIn(List<Integer> values) {
            addCriterion("userrank in", values, "userrank");
            return (Criteria) this;
        }

        public Criteria andUserrankNotIn(List<Integer> values) {
            addCriterion("userrank not in", values, "userrank");
            return (Criteria) this;
        }

        public Criteria andUserrankBetween(Integer value1, Integer value2) {
            addCriterion("userrank between", value1, value2, "userrank");
            return (Criteria) this;
        }

        public Criteria andUserrankNotBetween(Integer value1, Integer value2) {
            addCriterion("userrank not between", value1, value2, "userrank");
            return (Criteria) this;
        }

        public Criteria andAdminIsNull() {
            addCriterion("admin is null");
            return (Criteria) this;
        }

        public Criteria andAdminIsNotNull() {
            addCriterion("admin is not null");
            return (Criteria) this;
        }

        public Criteria andAdminEqualTo(Integer value) {
            addCriterion("admin =", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotEqualTo(Integer value) {
            addCriterion("admin <>", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThan(Integer value) {
            addCriterion("admin >", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminGreaterThanOrEqualTo(Integer value) {
            addCriterion("admin >=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThan(Integer value) {
            addCriterion("admin <", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminLessThanOrEqualTo(Integer value) {
            addCriterion("admin <=", value, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminIn(List<Integer> values) {
            addCriterion("admin in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotIn(List<Integer> values) {
            addCriterion("admin not in", values, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminBetween(Integer value1, Integer value2) {
            addCriterion("admin between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andAdminNotBetween(Integer value1, Integer value2) {
            addCriterion("admin not between", value1, value2, "admin");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andVipIsNull() {
            addCriterion("vip is null");
            return (Criteria) this;
        }

        public Criteria andVipIsNotNull() {
            addCriterion("vip is not null");
            return (Criteria) this;
        }

        public Criteria andVipEqualTo(Integer value) {
            addCriterion("vip =", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipNotEqualTo(Integer value) {
            addCriterion("vip <>", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipGreaterThan(Integer value) {
            addCriterion("vip >", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipGreaterThanOrEqualTo(Integer value) {
            addCriterion("vip >=", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipLessThan(Integer value) {
            addCriterion("vip <", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipLessThanOrEqualTo(Integer value) {
            addCriterion("vip <=", value, "vip");
            return (Criteria) this;
        }

        public Criteria andVipIn(List<Integer> values) {
            addCriterion("vip in", values, "vip");
            return (Criteria) this;
        }

        public Criteria andVipNotIn(List<Integer> values) {
            addCriterion("vip not in", values, "vip");
            return (Criteria) this;
        }

        public Criteria andVipBetween(Integer value1, Integer value2) {
            addCriterion("vip between", value1, value2, "vip");
            return (Criteria) this;
        }

        public Criteria andVipNotBetween(Integer value1, Integer value2) {
            addCriterion("vip not between", value1, value2, "vip");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 20 12:59:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}