package com.sanelee.zhiyuan.Mapper;

import com.sanelee.zhiyuan.Model.Profession;
import com.sanelee.zhiyuan.Model.ProfessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProfessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    long countByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int deleteByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int insert(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int insertSelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    List<Profession> selectByExampleWithBLOBsWithRowbounds(ProfessionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    List<Profession> selectByExampleWithBLOBs(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    List<Profession> selectByExampleWithRowbounds(ProfessionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    List<Profession> selectByExample(ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    Profession selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") Profession record, @Param("example") ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Profession record, @Param("example") ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByExample(@Param("record") Profession record, @Param("example") ProfessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByPrimaryKeySelective(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Profession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table profession
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByPrimaryKey(Profession record);
}