package com.sanelee.zhiyuan.Mapper;

import com.sanelee.zhiyuan.Model.School;
import com.sanelee.zhiyuan.Model.SchoolExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SchoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    long countByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int deleteByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int deleteByPrimaryKey(Integer scid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int insert(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int insertSelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    List<School> selectByExampleWithBLOBsWithRowbounds(SchoolExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    List<School> selectByExampleWithBLOBs(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    List<School> selectByExampleWithRowbounds(SchoolExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    List<School> selectByExample(SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    School selectByPrimaryKey(Integer scid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") School record, @Param("example") SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") School record, @Param("example") SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByExample(@Param("record") School record, @Param("example") SchoolExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByPrimaryKeySelective(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(School record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated Fri Dec 20 12:59:45 CST 2019
     */
    int updateByPrimaryKey(School record);
}